name: edupay_app
description: A Flutter frontend for EduPay school management app.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For making HTTP requests to the backend
  http: ^1.2.1 
  
  # For local storage (e.g., storing JWT token)
  shared_preferences: ^2.2.3 
  
  # For icons
  cupertino_icons: ^1.0.8 
  
  # For date formatting in receipt_view_page.dart
  intl: ^0.19.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Add the Inter font if you plan to use it (download and place in assets/fonts)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
